Already on 'master'
Client-Request-ID=ae565c9b-6bfe-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 16:03:43 GMT, Server-Request-ID=d24ed656-101e-00e6-6f0b-0045c1000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:d24ed656-101e-00e6-6f0b-0045c1000000Time:2018-06-09T16:03:43.1384246Z</Message></Error>.
Client-Request-ID=ae565c9d-6bfe-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 16:03:42 GMT, Server-Request-ID=719e157c-f01e-0081-510b-00f666000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:719e157c-f01e-0081-510b-00f666000000Time:2018-06-09T16:03:43.2972759Z</Message></Error>.
Client-Request-ID=ae565c9f-6bfe-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 16:03:42 GMT, Server-Request-ID=f0f1cd5e-401e-00dc-0a0b-000662000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:f0f1cd5e-401e-00dc-0a0b-000662000000Time:2018-06-09T16:03:43.4563298Z</Message></Error>.
Client-Request-ID=ae565ca1-6bfe-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 16:03:42 GMT, Server-Request-ID=a1ca35d4-901e-0019-780b-007859000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:a1ca35d4-901e-0019-780b-007859000000Time:2018-06-09T16:03:43.6178907Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Sat, 09 Jun 2018 16:05:34 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': 'f02edbc9846847ce8edd20b5dcdd28d0', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs01a"}]}'
Client-Request-ID=65224c8c-6c03-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 16:37:26 GMT, Server-Request-ID=e25e8352-201e-0126-2c10-0089d0000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:e25e8352-201e-0126-2c10-0089d0000000Time:2018-06-09T16:37:27.3352138Z</Message></Error>.
Client-Request-ID=65224c8e-6c03-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 16:37:27 GMT, Server-Request-ID=0d195263-601e-0061-6c10-0010ee000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:0d195263-601e-0061-6c10-0010ee000000Time:2018-06-09T16:37:27.4926078Z</Message></Error>.
Client-Request-ID=65224c90-6c03-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 16:37:27 GMT, Server-Request-ID=825e5671-901e-009a-4b10-00d8f4000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:825e5671-901e-009a-4b10-00d8f4000000Time:2018-06-09T16:37:27.6538174Z</Message></Error>.
Client-Request-ID=65224c92-6c03-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 16:37:26 GMT, Server-Request-ID=6b19421c-c01e-00ab-0810-008323000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:6b19421c-c01e-00ab-0810-008323000000Time:2018-06-09T16:37:27.8167479Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./10.o16n.py", line 64, in <module>
    image = image)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Sat, 09 Jun 2018 16:39:19 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '02905ae7f4884dbdb323115d46661b96', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs02"}]}'
Already on 'master'
