Switched to branch 'daily'
Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 133, in <module>
    service = ws.deploy_webservice(name = web_service_name,
AttributeError: 'Workspace' object has no attribute 'deploy_webservice'
Traceback (most recent call last):
  File "./02.local.py", line 51, in <module>
    script_to_run = train_script)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/run.py", line 72, in submit
    return _commands.start_run(project_object, run_config_object, telemetry_values=_telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 110, in start_run
    telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 274, in _start_internal_local_cloud
    snapshot_id = snapshot_async.get() if snapshot_async else None
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 120, in create_snapshot
    raise SnapshotException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.SnapshotException: {
    "status_code": 500,
    "text": {
        "correlation": {
            "operation": "f1b747fe-445cc8f0dd908cb8",
            "request": "rOyLKwmlDZw="
        },
        "error": {
            "code": "ServiceError",
            "debugInfo": {
                "data": {},
                "errorResponse": null,
                "innerException": null,
                "message": "The specified container does not exist.",
                "stackTrace": "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass31_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.SnapshotBlobProvider.<PutFileBlob>d__4.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotBlobProvider.cs:line 60\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.NewSnapshotFilesWriter.<SaveDeltaFiles>d__3.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/NewSnapshotFilesWriter.cs:line 58\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 210\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()",
                "type": "Microsoft.WindowsAzure.Storage.StorageException"
            },
            "details": [],
            "innerError": null,
            "message": "InternalServerError",
            "target": null
        }
    },
    "url": "https://eastus2euap.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/snapshots/c082af94-01a7-4e03-8ee0-e7fa083968d7?parentSnapshotId=45ad0386-55c9-4681-b7ec-027c8ba0decd"
}
Traceback (most recent call last):
  File "./03.aci.py", line 85, in <module>
    script_to_run = train_script)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/run.py", line 72, in submit
    return _commands.start_run(project_object, run_config_object, telemetry_values=_telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 115, in start_run
    telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 384, in _start_internal
    snapshot_id = snapshot_async.get() if snapshot_async else None
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 120, in create_snapshot
    raise SnapshotException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.SnapshotException: {
    "status_code": 500,
    "text": {
        "correlation": {
            "operation": "8bf471c9-42a5ca1c51c6d988",
            "request": "yAQgYBE8HPU="
        },
        "error": {
            "code": "ServiceError",
            "debugInfo": {
                "data": {},
                "errorResponse": null,
                "innerException": null,
                "message": "The specified container does not exist.",
                "stackTrace": "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass31_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.SnapshotBlobProvider.<PutFileBlob>d__4.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotBlobProvider.cs:line 60\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.NewSnapshotFilesWriter.<SaveDeltaFiles>d__3.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/NewSnapshotFilesWriter.cs:line 58\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 210\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()",
                "type": "Microsoft.WindowsAzure.Storage.StorageException"
            },
            "details": [],
            "innerError": null,
            "message": "InternalServerError",
            "target": null
        }
    },
    "url": "https://eastus2euap.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/snapshots/dedeed60-f9cb-4221-8217-857279a57125?parentSnapshotId=55c9c171-7b49-43c2-b623-b2e822f9907b"
}
Traceback (most recent call last):
  File "./04.dsvm.py", line 70, in <module>
    script_to_run = train_script)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/run.py", line 72, in submit
    return _commands.start_run(project_object, run_config_object, telemetry_values=_telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 115, in start_run
    telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 384, in _start_internal
    snapshot_id = snapshot_async.get() if snapshot_async else None
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 120, in create_snapshot
    raise SnapshotException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.SnapshotException: {
    "status_code": 500,
    "text": {
        "correlation": {
            "operation": "f1b74800-445cc8f0dd908cb8",
            "request": "eMJuy4ldvjQ="
        },
        "error": {
            "code": "ServiceError",
            "debugInfo": {
                "data": {},
                "errorResponse": null,
                "innerException": null,
                "message": "The specified container does not exist.",
                "stackTrace": "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass31_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.SnapshotBlobProvider.<PutFileBlob>d__4.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotBlobProvider.cs:line 60\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.NewSnapshotFilesWriter.<SaveDeltaFiles>d__3.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/NewSnapshotFilesWriter.cs:line 58\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 210\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()",
                "type": "Microsoft.WindowsAzure.Storage.StorageException"
            },
            "details": [],
            "innerError": null,
            "message": "InternalServerError",
            "target": null
        }
    },
    "url": "https://eastus2euap.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/snapshots/858910b8-0b1f-4964-a91e-c0e2497b77a2?parentSnapshotId=d9fa0027-1375-4afc-8dde-fab7955c0676"
}
Traceback (most recent call last):
  File "./05.spark.py", line 81, in <module>
    script_to_run = "train-spark.py")
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/run.py", line 72, in submit
    return _commands.start_run(project_object, run_config_object, telemetry_values=_telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 115, in start_run
    telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 384, in _start_internal
    snapshot_id = snapshot_async.get() if snapshot_async else None
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 120, in create_snapshot
    raise SnapshotException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.SnapshotException: {
    "status_code": 500,
    "text": {
        "correlation": {
            "operation": "fb8e7f35-4a81b652c36aa900",
            "request": "ZJtYlGHPGdY="
        },
        "error": {
            "code": "ServiceError",
            "debugInfo": {
                "data": {},
                "errorResponse": null,
                "innerException": null,
                "message": "The specified container does not exist.",
                "stackTrace": "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass31_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.SnapshotBlobProvider.<PutFileBlob>d__4.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotBlobProvider.cs:line 60\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.NewSnapshotFilesWriter.<SaveDeltaFiles>d__3.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/NewSnapshotFilesWriter.cs:line 58\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 210\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()",
                "type": "Microsoft.WindowsAzure.Storage.StorageException"
            },
            "details": [],
            "innerError": null,
            "message": "InternalServerError",
            "target": null
        }
    },
    "url": "https://eastus2euap.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/snapshots/1b688166-d7a1-4ae9-adad-44dee9e64002?parentSnapshotId=ee1a8833-9b97-4a28-b0ae-3c97e3d60106"
}
Traceback (most recent call last):
  File "./07.sklearn.hd.py", line 47, in <module>
    for ct in ws.list_compute_targets():
AttributeError: 'Workspace' object has no attribute 'list_compute_targets'
Traceback (most recent call last):
  File "./08.tf.hd.py", line 48, in <module>
    for ct in ws.list_compute_targets():
AttributeError: 'Workspace' object has no attribute 'list_compute_targets'
Traceback (most recent call last):
  File "./10.o16n.py", line 30, in <module>
    model = ws.register_model(model_path = "best_model.pkl",
AttributeError: 'Workspace' object has no attribute 'register_model'
Switched to branch 'master'
