Switched to branch 'candidate'
Client-Request-ID=43685e9f-6a53-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 13:04:08 GMT, Server-Request-ID=87c83f4a-201e-0088-0760-feece8000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:87c83f4a-201e-0088-0760-feece8000000Time:2018-06-07T13:04:08.7156962Z</Message></Error>.
Client-Request-ID=43685ea1-6a53-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 13:04:08 GMT, Server-Request-ID=60d9b0e0-601e-00ad-2d60-fe745b000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:60d9b0e0-601e-00ad-2d60-fe745b000000Time:2018-06-07T13:04:08.9344070Z</Message></Error>.
Client-Request-ID=43685ea3-6a53-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 13:04:08 GMT, Server-Request-ID=70566bde-f01e-0046-1560-fe8aa7000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:70566bde-f01e-0046-1560-fe8aa7000000Time:2018-06-07T13:04:09.1097492Z</Message></Error>.
Client-Request-ID=43685ea5-6a53-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 13:04:09 GMT, Server-Request-ID=142f8bdf-801e-00a7-4560-fe6dd2000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:142f8bdf-801e-00a7-4560-fe6dd2000000Time:2018-06-07T13:04:09.3224522Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Thu, 07 Jun 2018 13:05:52 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '04620ab9e0b942e08920f193754885b2', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs01a"}]}'
Traceback (most recent call last):
  File "./07.sklearn.hd.py", line 88, in <module>
    run = sk_est.fit()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/train/estimator.py", line 438, in fit
    return super(Estimator, self).fit()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/train/estimator.py", line 78, in fit
    _telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/run.py", line 66, in submit
    execute_with_zip=_execute_with_zip)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/execution/_commands.py", line 116, in start_run
    execute_with_zip=execute_with_zip)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/execution/_commands.py", line 383, in _start_internal
    _raise_request_error(response, "starting run")
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/execution/_commands.py", line 729, in _raise_request_error
    raise ExperimentExecutionException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.ExperimentExecutionException: {
    "url": "https://eastus2.experiments.azureml.net/execution/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/projects/e2e-07/run",
    "status_code": 502,
    "text": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
}
Client-Request-ID=42ea93f1-6a59-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 13:47:05 GMT, Server-Request-ID=925bbdb0-d01e-0111-5466-fe257f000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:925bbdb0-d01e-0111-5466-fe257f000000Time:2018-06-07T13:47:06.0540397Z</Message></Error>.
Client-Request-ID=44064343-6a59-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 13:47:06 GMT, Server-Request-ID=c961a015-901e-011d-3766-fecb8e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:c961a015-901e-011d-3766-fecb8e000000Time:2018-06-07T13:47:06.2257812Z</Message></Error>.
Client-Request-ID=44064345-6a59-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 13:47:05 GMT, Server-Request-ID=8f44d706-501e-00c8-6366-fec506000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:8f44d706-501e-00c8-6366-fec506000000Time:2018-06-07T13:47:06.4113008Z</Message></Error>.
Client-Request-ID=44064347-6a59-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 13:47:05 GMT, Server-Request-ID=b3adea25-a01e-00d6-5966-fe1feb000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:b3adea25-a01e-00d6-5966-fe1feb000000Time:2018-06-07T13:47:06.6007787Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Thu, 07 Jun 2018 13:52:26 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '786793e7fcff4c58a44f6bd070510994', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:26 can not be deleted because it is currently being used in one or more images"}]}'
error: Your local changes to the following files would be overwritten by checkout:
	e2e_test/best_model.pkl
	e2e_test/mse_over_alpha.png
Please, commit your changes or stash them before you can switch branches.
Aborting
