Already on 'master'
Client-Request-ID=aec21515-6c41-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sun, 10 Jun 2018 00:03:20 GMT, Server-Request-ID=99974184-b01e-00a4-1a4e-006ed5000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:99974184-b01e-00a4-1a4e-006ed5000000Time:2018-06-10T00:03:20.6715411Z</Message></Error>.
Client-Request-ID=aec21517-6c41-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sun, 10 Jun 2018 00:03:20 GMT, Server-Request-ID=bfde8d49-b01e-008d-304e-001897000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:bfde8d49-b01e-008d-304e-001897000000Time:2018-06-10T00:03:20.8714194Z</Message></Error>.
Client-Request-ID=aec21519-6c41-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sun, 10 Jun 2018 00:03:20 GMT, Server-Request-ID=248c2b54-301e-0110-454e-002482000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:248c2b54-301e-0110-454e-002482000000Time:2018-06-10T00:03:21.0502658Z</Message></Error>.
Client-Request-ID=afaab8bf-6c41-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sun, 10 Jun 2018 00:03:21 GMT, Server-Request-ID=da7ce82f-601e-0108-2a4e-000917000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:da7ce82f-601e-0108-2a4e-000917000000Time:2018-06-10T00:03:21.2604136Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Sun, 10 Jun 2018 00:04:56 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '0ad6cf4ade5c4e8c872f4c2878528778', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs01a"}]}'
Client-Request-ID=40bf02cb-6c46-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sun, 10 Jun 2018 00:36:03 GMT, Server-Request-ID=24932d61-301e-0110-3653-002482000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:24932d61-301e-0110-3653-002482000000Time:2018-06-10T00:36:04.0873332Z</Message></Error>.
Client-Request-ID=41ba4c8f-6c46-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sun, 10 Jun 2018 00:36:04 GMT, Server-Request-ID=da868a3f-601e-0108-0453-000917000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:da868a3f-601e-0108-0453-000917000000Time:2018-06-10T00:36:04.2717259Z</Message></Error>.
Client-Request-ID=41ba4c91-6c46-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sun, 10 Jun 2018 00:36:04 GMT, Server-Request-ID=2f477bf9-601e-0103-1c53-001163000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:2f477bf9-601e-0103-1c53-001163000000Time:2018-06-10T00:36:04.4314883Z</Message></Error>.
Client-Request-ID=41ba4c93-6c46-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sun, 10 Jun 2018 00:36:04 GMT, Server-Request-ID=bbd04efc-501e-00ea-0953-00ab30000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:bbd04efc-501e-00ea-0953-00ab30000000Time:2018-06-10T00:36:04.5902207Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./10.o16n.py", line 64, in <module>
    image = image)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Sun, 10 Jun 2018 00:37:40 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '7b6bb7051241464c94027ac069d2c8e9', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs02"}]}'
Already on 'master'
