Switched to branch 'daily'
Client-Request-ID=1cbb3635-6843-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 22:03:29 GMT, Server-Request-ID=a0ed03ab-b01e-0046-544f-fc112e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:a0ed03ab-b01e-0046-544f-fc112e000000Time:2018-06-04T22:03:30.0991368Z</Message></Error>.
Client-Request-ID=1d752aef-6843-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 22:03:30 GMT, Server-Request-ID=fb654010-b01e-0056-454f-fcd446000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:fb654010-b01e-0056-454f-fcd446000000Time:2018-06-04T22:03:30.2540638Z</Message></Error>.
Client-Request-ID=1d752af1-6843-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 22:03:29 GMT, Server-Request-ID=f3ca43fa-c01e-0087-344f-fcb6cc000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:f3ca43fa-c01e-0087-344f-fcb6cc000000Time:2018-06-04T22:03:30.4099705Z</Message></Error>.
Client-Request-ID=1d752af3-6843-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 22:03:29 GMT, Server-Request-ID=2439cf3d-a01e-0017-044f-fc8ca2000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:2439cf3d-a01e-0017-044f-fc8ca2000000Time:2018-06-04T22:03:30.5672747Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2euap.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Mon, 04 Jun 2018 22:04:51 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': 'de4e25c41a6e4929aad07c85880db976', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2euapws already contains a Service with name: rrs01a"}]}'
Traceback (most recent call last):
  File "./03.aci.py", line 97, in <module>
    min(metrics['mse']), 
KeyError: 'mse'
Client-Request-ID=e347e33b-6846-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 22:30:31 GMT, Server-Request-ID=ae0de20a-001e-006c-3453-fcce3e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:ae0de20a-001e-006c-3453-fcce3e000000Time:2018-06-04T22:30:32.0905390Z</Message></Error>.
Client-Request-ID=e43d767f-6846-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 22:30:31 GMT, Server-Request-ID=cf81aacd-401e-000f-4253-fc53c5000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:cf81aacd-401e-000f-4253-fc53c5000000Time:2018-06-04T22:30:32.2451797Z</Message></Error>.
Client-Request-ID=e43d7681-6846-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 22:30:32 GMT, Server-Request-ID=d04cc312-101e-0070-4d53-fc9c5e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:d04cc312-101e-0070-4d53-fc9c5e000000Time:2018-06-04T22:30:32.4028747Z</Message></Error>.
Client-Request-ID=e43d7683-6846-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 22:30:32 GMT, Server-Request-ID=2c0cf216-901e-000c-4153-fcb2a1000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:2c0cf216-901e-000c-4153-fcb2a1000000Time:2018-06-04T22:30:32.5627598Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Mon, 04 Jun 2018 22:36:58 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '3b93ad86e61b46f9a81e0ec6a9f86668', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:1 can not be deleted because it is currently being used in one or more images"}]}'
Switched to branch 'master'
