Switched to branch 'daily'
Client-Request-ID=2bc215d9-6886-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 06:03:30 GMT, Server-Request-ID=5ec8790b-a01e-005a-5692-fc434e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:5ec8790b-a01e-005a-5692-fc434e000000Time:2018-06-05T06:03:31.2290468Z</Message></Error>.
Client-Request-ID=2bc215db-6886-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 06:03:30 GMT, Server-Request-ID=cecc4bda-201e-0019-1192-fca512000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:cecc4bda-201e-0019-1192-fca512000000Time:2018-06-05T06:03:31.3891152Z</Message></Error>.
Client-Request-ID=2bc215dd-6886-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 06:03:31 GMT, Server-Request-ID=d6c2d0cb-801e-0086-3c92-fce910000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:d6c2d0cb-801e-0086-3c92-fce910000000Time:2018-06-05T06:03:31.5450943Z</Message></Error>.
Client-Request-ID=2bc215df-6886-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 06:03:30 GMT, Server-Request-ID=563e0b1f-701e-002b-7592-fca565000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:563e0b1f-701e-002b-7592-fca565000000Time:2018-06-05T06:03:31.7005926Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2euap.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Tue, 05 Jun 2018 06:04:56 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '35471c9f7eea4defbc4cc61e3675ae2a', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2euapws already contains a Service with name: rrs01a"}]}'
Client-Request-ID=45a62d00-688a-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 06:32:51 GMT, Server-Request-ID=563e8792-701e-002b-5297-fca565000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:563e8792-701e-002b-5297-fca565000000Time:2018-06-05T06:32:51.9172268Z</Message></Error>.
Client-Request-ID=45a62d02-688a-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 06:32:51 GMT, Server-Request-ID=b12361be-101e-004f-1997-fc54fd000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:b12361be-101e-004f-1997-fc54fd000000Time:2018-06-05T06:32:52.0747241Z</Message></Error>.
Client-Request-ID=45a62d04-688a-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 06:32:52 GMT, Server-Request-ID=e9a22173-e01e-0029-6697-fc1bdd000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:e9a22173-e01e-0029-6697-fc1bdd000000Time:2018-06-05T06:32:52.2309246Z</Message></Error>.
Client-Request-ID=45a62d06-688a-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 06:32:51 GMT, Server-Request-ID=74756ed0-b01e-0024-3597-fcd309000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:74756ed0-b01e-0024-3597-fcd309000000Time:2018-06-05T06:32:52.3895615Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Tue, 05 Jun 2018 06:35:00 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '7e14296f3beb47ac909ec9b472bb221a', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:1 can not be deleted because it is currently being used in one or more images"}]}'
Switched to branch 'master'
