Switched to branch 'daily'
Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 133, in <module>
    service = ws.deploy_webservice(name = web_service_name,
AttributeError: 'Workspace' object has no attribute 'deploy_webservice'
Traceback (most recent call last):
  File "./02.local.py", line 51, in <module>
    script_to_run = train_script)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/run.py", line 70, in submit
    return _commands.start_run(project_object, run_config_object, telemetry_values=_telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 110, in start_run
    telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 274, in _start_internal_local_cloud
    snapshot_id = snapshot_async.get() if snapshot_async else None
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 120, in create_snapshot
    raise SnapshotException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.SnapshotException: {
    "status_code": 500,
    "text": {
        "correlation": {
            "operation": "27112969-47624fb41f18297e",
            "request": "PpmjFjm3Cek="
        },
        "error": {
            "code": "ServiceError",
            "debugInfo": {
                "data": {},
                "errorResponse": null,
                "innerException": null,
                "message": "The specified container does not exist.",
                "stackTrace": "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass31_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.SnapshotBlobProvider.<PutFileBlob>d__4.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotBlobProvider.cs:line 60\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.NewSnapshotFilesWriter.<SaveDeltaFiles>d__3.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/NewSnapshotFilesWriter.cs:line 58\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 210\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()",
                "type": "Microsoft.WindowsAzure.Storage.StorageException"
            },
            "details": [],
            "innerError": null,
            "message": "InternalServerError",
            "target": null
        }
    },
    "url": "https://eastus2euap.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/snapshots/91d02ee7-abd8-419e-8dc4-618d1895267b?parentSnapshotId=45ad0386-55c9-4681-b7ec-027c8ba0decd"
}
Traceback (most recent call last):
  File "./03.aci.py", line 85, in <module>
    script_to_run = train_script)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/run.py", line 70, in submit
    return _commands.start_run(project_object, run_config_object, telemetry_values=_telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 115, in start_run
    telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 384, in _start_internal
    snapshot_id = snapshot_async.get() if snapshot_async else None
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 120, in create_snapshot
    raise SnapshotException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.SnapshotException: {
    "status_code": 500,
    "text": {
        "correlation": {
            "operation": "80b2ce9d-488d9dd5ac911330",
            "request": "auQuhby5wn0="
        },
        "error": {
            "code": "ServiceError",
            "debugInfo": {
                "data": {},
                "errorResponse": null,
                "innerException": null,
                "message": "The specified container does not exist.",
                "stackTrace": "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass31_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.SnapshotBlobProvider.<PutFileBlob>d__4.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotBlobProvider.cs:line 60\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.NewSnapshotFilesWriter.<SaveDeltaFiles>d__3.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/NewSnapshotFilesWriter.cs:line 58\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 210\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()",
                "type": "Microsoft.WindowsAzure.Storage.StorageException"
            },
            "details": [],
            "innerError": null,
            "message": "InternalServerError",
            "target": null
        }
    },
    "url": "https://eastus2euap.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/snapshots/897cb23b-3cc5-41c6-abbb-4d3bf6195b07?parentSnapshotId=55c9c171-7b49-43c2-b623-b2e822f9907b"
}
Traceback (most recent call last):
  File "./04.dsvm.py", line 70, in <module>
    script_to_run = train_script)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/run.py", line 70, in submit
    return _commands.start_run(project_object, run_config_object, telemetry_values=_telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 115, in start_run
    telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 384, in _start_internal
    snapshot_id = snapshot_async.get() if snapshot_async else None
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 120, in create_snapshot
    raise SnapshotException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.SnapshotException: {
    "status_code": 500,
    "text": {
        "correlation": {
            "operation": "50d8f760-42c5dbed47ea87b5",
            "request": "WjY7ml3wI9w="
        },
        "error": {
            "code": "ServiceError",
            "debugInfo": {
                "data": {},
                "errorResponse": null,
                "innerException": null,
                "message": "The specified container does not exist.",
                "stackTrace": "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass31_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.SnapshotBlobProvider.<PutFileBlob>d__4.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotBlobProvider.cs:line 60\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.NewSnapshotFilesWriter.<SaveDeltaFiles>d__3.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/NewSnapshotFilesWriter.cs:line 58\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 210\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()",
                "type": "Microsoft.WindowsAzure.Storage.StorageException"
            },
            "details": [],
            "innerError": null,
            "message": "InternalServerError",
            "target": null
        }
    },
    "url": "https://eastus2euap.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/snapshots/35d6234e-30df-4848-a8ba-12cc56c8cc35?parentSnapshotId=d9fa0027-1375-4afc-8dde-fab7955c0676"
}
Traceback (most recent call last):
  File "./05.spark.py", line 81, in <module>
    script_to_run = "train-spark.py")
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/run.py", line 70, in submit
    return _commands.start_run(project_object, run_config_object, telemetry_values=_telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 115, in start_run
    telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/execution/_commands.py", line 384, in _start_internal
    snapshot_id = snapshot_async.get() if snapshot_async else None
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 120, in create_snapshot
    raise SnapshotException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.SnapshotException: {
    "status_code": 500,
    "text": {
        "correlation": {
            "operation": "8560d6f5-4fd3626b0e196ba2",
            "request": "ORU6kpEYC5s="
        },
        "error": {
            "code": "ServiceError",
            "debugInfo": {
                "data": {},
                "errorResponse": null,
                "innerException": null,
                "message": "The specified container does not exist.",
                "stackTrace": "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass31_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.SnapshotBlobProvider.<PutFileBlob>d__4.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotBlobProvider.cs:line 60\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.Services.NewSnapshotFilesWriter.<SaveDeltaFiles>d__3.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/NewSnapshotFilesWriter.cs:line 58\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 210\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()",
                "type": "Microsoft.WindowsAzure.Storage.StorageException"
            },
            "details": [],
            "innerError": null,
            "message": "InternalServerError",
            "target": null
        }
    },
    "url": "https://eastus2euap.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/snapshots/cd0bcede-0ef5-40a1-9818-e2ad0859eb22?parentSnapshotId=ee1a8833-9b97-4a28-b0ae-3c97e3d60106"
}
Traceback (most recent call last):
  File "./07.sklearn.hd.py", line 47, in <module>
    for ct in ws.list_compute_targets():
AttributeError: 'Workspace' object has no attribute 'list_compute_targets'
Traceback (most recent call last):
  File "./08.tf.hd.py", line 48, in <module>
    for ct in ws.list_compute_targets():
AttributeError: 'Workspace' object has no attribute 'list_compute_targets'
Traceback (most recent call last):
  File "./10.o16n.py", line 30, in <module>
    model = ws.register_model(model_path = "best_model.pkl",
AttributeError: 'Workspace' object has no attribute 'register_model'
Switched to branch 'master'
