Already on 'master'
Client-Request-ID=35863071-6c20-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 20:03:43 GMT, Server-Request-ID=2f2e6798-601e-0103-122c-001163000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:2f2e6798-601e-0103-122c-001163000000Time:2018-06-09T20:03:43.3394801Z</Message></Error>.
Client-Request-ID=35863073-6c20-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 20:03:43 GMT, Server-Request-ID=1746cf6a-501e-008c-3f2c-00196a000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:1746cf6a-501e-008c-3f2c-00196a000000Time:2018-06-09T20:03:43.5386100Z</Message></Error>.
Client-Request-ID=35863075-6c20-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 20:03:43 GMT, Server-Request-ID=f5f371a3-001e-0113-172c-002785000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:f5f371a3-001e-0113-172c-002785000000Time:2018-06-09T20:03:43.7024894Z</Message></Error>.
Client-Request-ID=35863077-6c20-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 20:03:43 GMT, Server-Request-ID=44a0e3ce-201e-00aa-2b2c-0082de000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:44a0e3ce-201e-00aa-2b2c-0082de000000Time:2018-06-09T20:03:44.0139663Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Sat, 09 Jun 2018 20:05:14 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '862b1e0d0fc14fb8bd4e2d5dd6b01e41', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs01a"}]}'
Client-Request-ID=f9f12b47-6c24-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 20:37:51 GMT, Server-Request-ID=48f3691e-501e-00a5-7131-006f28000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:48f3691e-501e-00a5-7131-006f28000000Time:2018-06-09T20:37:51.9120353Z</Message></Error>.
Client-Request-ID=f9f12b49-6c24-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 20:37:51 GMT, Server-Request-ID=b7a84b05-e01e-0052-1931-0049c3000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:b7a84b05-e01e-0052-1931-0049c3000000Time:2018-06-09T20:37:52.0736531Z</Message></Error>.
Client-Request-ID=fb06f1f1-6c24-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 20:37:51 GMT, Server-Request-ID=15ec7423-701e-00f6-0431-007327000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:15ec7423-701e-00f6-0431-007327000000Time:2018-06-09T20:37:52.2344897Z</Message></Error>.
Client-Request-ID=fb06f1f3-6c24-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Sat, 09 Jun 2018 20:37:51 GMT, Server-Request-ID=fb35e7ac-c01e-00e4-0a31-00473b000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:fb35e7ac-c01e-00e4-0a31-00473b000000Time:2018-06-09T20:37:52.4452287Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./10.o16n.py", line 64, in <module>
    image = image)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Sat, 09 Jun 2018 20:39:23 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '8903c26f96aa4e54a2fa7eb8fe460e3f', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs02"}]}'
Already on 'master'
